use crate::{
    codestr::Code,
    config::{ConfigJson, ConfigServerJson},
};

use std::fmt::Write;

fn create_nginx_block(
    code: &mut Code,
    domain: &String,
    server: &ConfigServerJson,
) -> Result<(), std::fmt::Error> {
    write!(
        code,
        "# {}: {} ({})",
        server.port,
        server.name,
        server.subdomain.as_deref().unwrap_or("None")
    )?;

    code.add_line("server {");
    code.indent();

    if server.ssl.is_some() {
        code.add_line("listen 443;");
    } else {
        code.add_line("listen 80;");
    }

    code.newline();

    write!(
        code,
        "# Subdomain extension {}",
        if server.allow_sub_ext {
            "enabled"
        } else {
            "disabled"
        }
    )?;

    let sub_ext = server.allow_sub_ext.then_some("(_[0-9]+)?");

    write!(
        code,
        "server_name ~^{}{}{}$;",
        sub_ext.unwrap_or_default(),
        server
            .subdomain
            .as_deref()
            .map(|s| format!("{s}\\."))
            .unwrap_or_default(),
        domain
    )?;

    if let Some(ssl) = &server.ssl {
        write!(code, "ssl_certificate {};", ssl.cert)?;
        write!(
            code,
            "ssl_certificate_key {};",
            ssl.key.as_ref().unwrap_or(&ssl.cert)
        )?;
    }

    code.newline();
    code.add_line("location / {");
    code.indent();

    write!(code, "proxy_pass http://127.0.0.1:{}/;", server.port)?;
    code.add_line("proxy_set_header Host $host;");

    if server.websocket {
        code.add_line("proxy_http_version 1.1;");
        code.add_line("proxy_set_header Upgrade $http_upgrade;");
        code.add_line("proxy_set_header Connection $connection_upgrade;");
    }

    code.outdent();
    code.add_line("}");
    code.outdent();
    code.add_line("}");

    Ok(())
}

pub fn generate_nginx_file(config: &ConfigJson) -> String {
    let mut code = Code::new(4096);
    code.add_line("# Autogenerated");
    write!(code, "# Servers: {}", config.servers.len()).unwrap();

    code.add_line("map $http_upgrade $connection_upgrade {");
    code.indent();
    code.add_line("default upgrade;");
    code.add_line("'' close;");
    code.outdent();
    code.add_line("}");

    let domain_escaped = config.domain.replace(".", "\\.");
    for server in &config.servers {
        code.newline();
        create_nginx_block(&mut code, &domain_escaped, server).expect("Error creating nginx block");
    }

    code.done()
}
