use crate::config::{ConfigJson, ConfigServerJson};

use std::fmt::Write;

fn create_nginx_block(
    domain: &String,
    server: &ConfigServerJson,
) -> Result<String, std::fmt::Error> {
    let mut block = String::with_capacity(512);

    write!(
        block,
        "# {}: {} ({})\n",
        server.port,
        server.name,
        server.subdomain.as_deref().unwrap_or("None")
    )?;

    block.push_str("server {\n\t");

    if server.ssl.is_some() {
        block.push_str("listen 443;\n\t");
    } else {
        block.push_str("listen 80;\n\t");
    }

    write!(
        block,
        "# Subdomain extension {}\n\tserver_name ~^{}",
        if server.allow_sub_ext {
            "enabled"
        } else {
            "disabled"
        },
        server.subdomain.as_deref().unwrap_or("")
    )?;

    if server.allow_sub_ext {
        block.push_str("(_[0-9]+)?");
    }

    if server.subdomain.is_some() {
        block.push_str("\\.");
    }

    write!(block, "{}$;\n\n\t", domain)?;

    if let Some(ssl) = &server.ssl {
        write!(
            block,
            "ssl_certificate {};\n\tssl_certificate_key {};\n\n\t",
            ssl.cert,
            ssl.key.as_ref().unwrap_or(&ssl.cert)
        )?;
    }

    block.push_str("location / {\n\t\t");

    write!(block, "proxy_pass http://127.0.0.1:{}/;\n\t\t", server.port)?;
    block.push_str("proxy_set_header Host $host;");

    if server.websocket {
        block.push_str(
            r#"
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
"#,
        );
    }

    block.push_str("\t}\n}");

    Ok(block)
}

pub fn generate_nginx_file(config: &ConfigJson) -> String {
    let mut output = String::with_capacity(4096);
    output.push_str("# Autogenerated\n");
    output.push_str(&format!("# Servers: {}\n", config.servers.len()));
    output.push_str(
        r#"map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
"#,
    );

    let domain_escaped = config.domain.replace(".", "\\.");
    for server in &config.servers {
        output.push_str("\n\n");
        output.push_str(
            &create_nginx_block(&domain_escaped, server).expect("Error creating nginx block"),
        );
    }

    output
}
