use crate::config::ConfigJson;

use std::fmt::Write;

pub fn generate_runall(config: &ConfigJson) -> Result<String, std::fmt::Error> {
    let mut runall = String::with_capacity(1024);
    runall.push_str("# Autogenerated\n");

    write!(runall, "# {} servers", config.servers.len())?;

    for server in &config.servers {
        let Some(run) = &server.run else {
            continue;
        };

        write!(
            runall,
            "\n# Server: {}\n# Venv: {}\n",
            server.name,
            if run.venv { "on" } else { "off" }
        )?;
        write!(runall, "cd {}\n", run.cwd)?;
        if run.venv {
            runall.push_str("source ./bin/activate\n");
        }
        runall.push_str(&run.command);
        if run.venv {
            runall.push_str("\ndeactivate");
        }
        runall.push('\n');
    }

    Ok(runall)
}
